### ISSUE TITLE
System.IO.IOException: Win32 IO returned ERROR_NOT_SUPPORTED. Path: /[Unknown]

### ISSUE THREAD

**Issue by ZeProgFactory** [ZeProgFactory/MediaPlayer#4]
<.ctor>b__7_0 (System.Object sender, Android.Media.MediaPlayer+ErrorEventArgs args)
D:\GitWare\Nugets\MediaPlayer\MediaPlayer\Platforms\Android\MediaPlayerImplementation.cs, line 37
System.IO.IOException: Win32 IO returned ERROR_NOT_SUPPORTED. Path: /[Unknown]

FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/FileStream.cs:636
FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/FileStream.cs:614
StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:335
StreamWriter.WriteSpan (System.ReadOnlySpan`1[T] buffer, System.Boolean appendNewLine) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:516
StreamWriter.WriteLine (System.String value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/StreamWriter.cs:530
TextWriter+SyncTextWriter.WriteLine (System.String value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/TextWriter.cs:817
(wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(string)
LogcatTextWriter.WriteLine () /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/LogcatTextWriter.cs:54
LogcatTextWriter.Write (System.Char value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/LogcatTextWriter.cs:43
LogcatTextWriter.Write (System.String s) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/LogcatTextWriter.cs:37
TextWriter.WriteLine (System.String value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/TextWriter.cs:463
TextWriter+SyncTextWriter.WriteLine (System.String value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/IO/TextWriter.cs:817
(wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(string)
Console.WriteLine (System.String value) /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System/Console.cs:432
<.ctor>b__7_0 (System.Object sender, Android.Media.MediaPlayer+ErrorEventArgs args) D:\GitWare\Nugets\MediaPlayer\MediaPlayer\Platforms\Android\MediaPlayerImplementation.cs:37
MediaPlayer+IOnErrorListenerImplementor.OnError (Android.Media.MediaPlayer mp, Android.Media.MediaError what, System.Int32 extra)
MediaPlayer+IOnErrorListenerInvoker.n_OnError_Landroid_media_MediaPlayer_II (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_mp, System.Int32 native_what, System.Int32 extra)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.83(intptr,intptr,intptr,int,int)

https://appcenter.ms/orgs/ZPF/apps/CallBooster-1/crashes/errors/3034046220u/overview

**Comment by jimmy-vo-librestream** [comment]
I have exactly the same issue. Is there any work around?

**Comment by ZeProgFactory** [comment]
Hi @jimmy-vo-librestream,
Unfortunately, the error occurred only once, and same code is working fine since ...
If you can create a test project I’ll investigate on this issue.
Thanks,
Michael
